#!/bin/bash
NSERVICE=kaigree
#export DOCKER_API_VERSION=1.23
PROD_DOCKER_HOST=tcp://master4g10.cs-cn-hangzhou.aliyun.com:20176
PROD_DOCKER_CERT_PATH=$HOME/.ssh/docker/yunshang

if [[ "$1" == "up" ]]; then
  $0 pull
  $0 build
fi

if [[ "$1" == "push" ]]; then
  if [[ "$2" == "wjdocker" ]]; then
    docker tag "ka-igree" wjdocker.lab/wanjia/kaigree
    docker push wjdocker.lab/wanjia/kaigree
  else
    docker tag "kg-igree_ka-igree" registry.cn-hangzhou.aliyuncs.com/yundian/kaigree:latest
    docker push registry.cn-hangzhou.aliyuncs.com/yundian/kaigree:latest
  fi
  exit
fi

if [[ "$1" == "--prod" ]]; then
   if [[ "$2" =~ ^(shell|attach|inspect|port|stats|top|ps)$ ]]; then
      SH=$4
      if [[ "$SH" == "" ]]; then
        SH=/bin/bash
      fi
      CT=$3
      if [[ "$CT" == "" ]]; then
        CT=kaigree
      fi

      if [[ "$CT" =~ _[0-9]+$ ]]; then
        echo
      else
        CT=${CT}_1
      fi

      if [[ "$2" == "shell" ]]; then
        if [[ "${3:0:1}" == ":" ]]; then
          DOCKER_TLS_VERIFY="1" DOCKER_CERT_PATH="$PROD_DOCKER_CERT_PATH" DOCKER_HOST="$PROD_DOCKER_HOST" docker exec -ti ${3:1} env LANG=C.UTF-8  $SH  "${@:5}"
        else
          DOCKER_TLS_VERIFY="1" DOCKER_CERT_PATH="$PROD_DOCKER_CERT_PATH" DOCKER_HOST="$PROD_DOCKER_HOST" docker exec -ti ${NSERVICE}_${CT} env LANG=C.UTF-8  $SH  "${@:5}"
        fi
      elif [[ "$2" == "ps" ]]; then
        DOCKER_TLS_VERIFY="1" DOCKER_CERT_PATH="$PROD_DOCKER_CERT_PATH" DOCKER_HOST="$PROD_DOCKER_HOST" docker ps $3
      elif [[ "$2" =~ ^(attach|inspect|port|stats|top)$ ]]; then
        DOCKER_TLS_VERIFY="1" DOCKER_CERT_PATH="$PROD_DOCKER_CERT_PATH" DOCKER_HOST="$PROD_DOCKER_HOST" docker $2 ${NSERVICE}_${CT}
      fi
      exit
   fi
else
  if [[ "$1" =~ ^(shell|attach|inspect|port|stats|top)$ ]]; then
    SH=$3
    if [[ "$SH" == "" ]]; then
      SH=/bin/bash
    fi
    CT=$2
    if [[ "$CT" == "" ]]; then
      CT=kaigree
    fi

    if [[ "$CT" =~ _[0-9]+$ ]]; then
      echo
    else
      CT=${CT}_1
    fi

    if [[ "$1" == "shell" ]]; then
      docker exec -ti ${NSERVICE}_${CT} env LANG=C.UTF-8  $SH
    elif [[ "$1" =~ ^(attach|inspect|port|stats|top)$ ]]; then
      docker $1 ${NSERVICE}_${CT}
    fi
    exit
  fi
fi

docker-compose -p $NSERVICE -f docker/docker-compose.yml $*
