#!/bin/bash
NSERVICE=laravel-docker


if [[ "$1" == "up" ]]; then
  $0 pull
  $0 build
fi


  if [[ "$1" =~ ^(shell|attach|inspect|port|stats|top)$ ]]; then
    SH=$3
    if [[ "$SH" == "" ]]; then
      SH=/bin/bash
    fi
    CT=$2
    if [[ "$CT" == "" ]]; then
      CT=laravel-docker
    fi

    if [[ "$CT" =~ _[0-9]+$ ]]; then
      echo
    else
      CT=${CT}_1
    fi

    if [[ "$1" == "shell" ]]; then
      docker exec -ti ${NSERVICE}_${CT} env LANG=C.UTF-8  $SH
    elif [[ "$1" =~ ^(attach|inspect|port|stats|top)$ ]]; then
      docker $1 ${NSERVICE}_${CT}
    fi
    exit
  fi

docker-compose -p $NSERVICE -f docker/docker-compose.yml $*
