#!/bin/bash

chmod -R a+rwX /var/log/nginx /var/log/php

if [[ ! -d /var/www/log/queue ]]; then
        mkdir /var/www/log/queue
        chmod 777 /var/www/log/queue
fi

if [[ ! -d /var/run/cron ]]; then
        mkdir /var/run/cron
        chmod 777 /var/run/cron
fi


declare -A roles
for constant in $APP_ROLE
do
    roles[$constant]=1
done

rm /var/spool/cron/crontabs/*
for constant in $APP_ROLE
do
    for file in $(find docker/crontabs -type f -name $constant:*); do
        IFS=':' read -r -a PARTS <<< $(basename $file)
        CRONTAB=/var/spool/cron/crontabs/${PARTS[1]}

        if [[ ! -f $CRONTAB ]]; then
            echo "SHELL=\"/bin/bash\"" > $CRONTAB
            echo "PATH=\"/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin\"" >> $CRONTAB
            echo "TZ=Asia/Shanghai" >> $CRONTAB
            echo "APP_ROLE=$APP_ROLE" >> $CRONTAB
        fi
        cat $file >> $CRONTAB
        echo >> $CRONTAB

        chown -R ${PARTS[1]}:crontab $CRONTAB
        chmod 600 $CRONTAB
    done
done


