#!/bin/bash

touch /root/.app_inited

mv /var/www /var/www.bk

ln -s /data/nas/codes/laravel-docker /var/www

./artisan config:cache
./artisan route:cache
./artisan optimize

touch /root/.app_laravel_inited

