laravel-docker: &phprunner
  restart: always
  image: registry.cn-hangzhou.aliyuncs.com/xiaoyao/laravel-phprunner:host
  volumes:
    - ~/xiaoyao/laravel-docker-conf:/data/nas/codes/confs
    - ~/Downloads/uploads:/data/uploads
    - $PWD:/var/www
  ports:
    - 6082:80
  extra_hosts:
    - "mysql:192.168.48.26"
    - "redis-server:192.168.48.26"
  environment: &phprunner-env
    cap-add: SYS_PTRACE
    APP_INIT_SCRIPT: /var/www/docker/app_init
    APP_START_SCRIPT: /var/www/docker/app_start

q-default:
  <<: *phprunner
  ports: []
  labels:
    aliyun.routing.port_80: 'http://qdaemon'       #QDaemon 服务不对外提供服务，但是要覆盖掉 laravel 服务中定义的字段
  environment:
    <<: *phprunner-env
    APP_ROLE: noweb nofpm q_default



